# Generated by Django 3.0.5 on 2020-04-09 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=300, null=True, unique=True)),
                ('amount', models.FloatField(blank=True, null=True, verbose_name='Ingredient|amount')),
                ('amountMax', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True, null=True)),
                ('modifiedAt', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(blank=True, max_length=500, null=True, unique=True)),
                ('prepTime', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('cookTime', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('imageURL', models.URLField(blank=True, max_length=300, null=True)),
                ('minServings', models.PositiveSmallIntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Recipe',
                'verbose_name_plural': 'Recipes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True, verbose_name='Unit|name')),
                ('name_abbrev', models.CharField(blank=True, max_length=60, verbose_name='Unit|name_abbrev')),
                ('plural_abbrev', models.CharField(blank=True, max_length=60, verbose_name='Unit|plural_abbrev')),
                ('type', models.IntegerField(choices=[(0, 'Other'), (1, 'Mass'), (2, 'Volume')])),
                ('system', models.IntegerField(choices=[(0, 'Metric'), (1, 'Imperial')], null=True)),
            ],
            options={
                'verbose_name': 'Unit',
                'verbose_name_plural': 'Units',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('text', models.TextField(blank=True, verbose_name='Direction|text')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='directions', to='recipe.Recipe')),
            ],
            options={
                'verbose_name': 'Direction',
                'verbose_name_plural': 'Directions',
                'ordering': ['order', 'id'],
            },
        ),
    ]
