# Generated by Django 3.0.5 on 2020-04-09 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='direction',
            options={'verbose_name': 'Direction', 'verbose_name_plural': 'Directions'},
        ),
    ]
