# Generated by Django 2.2.12 on 2020-04-30 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='large_image_url',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='med_image_url',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='sm_image_url',
        ),
    ]
