# Generated by Django 2.2.12 on 2020-04-30 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_auto_20200430_0559'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='placeholder_url',
            field=models.URLField(default='https://via.placeholder.com/400', max_length=300),
        ),
    ]
