# Generated by Django 3.0.5 on 2020-04-09 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_auto_20200409_1912'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='direction',
            options={'ordering': ('order',), 'verbose_name': 'Direction', 'verbose_name_plural': 'Directions'},
        ),
    ]
