# Generated by Django 3.0.5 on 2020-04-09 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0003_auto_20200409_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='direction',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
