# Generated by Django 3.0.5 on 2020-04-09 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0006_auto_20200409_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(blank=True, through='recipe.IngredientAmount', to='recipe.Ingredient'),
        ),
    ]
