# Generated by Django 2.2.12 on 2020-05-01 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0006_auto_20200501_2200'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='plural_abbrev',
            new_name='plural_name',
        ),
    ]
