# Generated by Django 3.0.5 on 2020-04-09 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0007_recipe_ingredients'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredientamount',
            old_name='amountPerServing',
            new_name='amount_per_serving',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='cookTime',
            new_name='cook_time',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='imageURL',
            new_name='image_url',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='minServings',
            new_name='min_servings',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='prepTime',
            new_name='prep_time',
        ),
    ]
