# Generated by Django 2.2.12 on 2020-05-01 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0007_auto_20200501_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='plural_name',
            field=models.CharField(blank=True, max_length=60, verbose_name='Plural name'),
        ),
    ]
