# Generated by Django 3.0.5 on 2020-04-09 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0008_auto_20200409_2030'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='min_servings',
            new_name='servings',
        ),
    ]
