# Generated by Django 3.0.5 on 2020-04-09 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0009_auto_20200409_2034'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredientamount',
            old_name='amount_per_serving',
            new_name='amount',
        ),
    ]
