# Generated by Django 2.2.12 on 2020-05-10 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0009_auto_20200502_0141'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nutrition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calories', models.PositiveSmallIntegerField(default=0)),
                ('carbs', models.PositiveSmallIntegerField(default=0)),
                ('cholestrol', models.PositiveSmallIntegerField(default=0)),
                ('fat', models.PositiveSmallIntegerField(default=0)),
                ('fiber', models.PositiveSmallIntegerField(default=0)),
                ('protein', models.PositiveSmallIntegerField(default=0)),
                ('sat_fat', models.PositiveSmallIntegerField(default=0)),
                ('servings', models.PositiveSmallIntegerField(default=0)),
                ('sodium', models.PositiveSmallIntegerField(default=0)),
                ('sugar', models.PositiveSmallIntegerField(default=0)),
                ('trans_fat', models.PositiveSmallIntegerField(default=0)),
                ('unsat_fat', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
    ]
