# Generated by Django 3.0.5 on 2020-04-10 02:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0010_auto_20200409_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='direction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingredients', to='recipe.Direction'),
        ),
    ]
