# Generated by Django 3.0.5 on 2020-04-10 02:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0011_ingredient_direction'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredientamount',
            name='quantity',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='quantity'),
        ),
        migrations.AddField(
            model_name='ingredientamount',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingredient_amounts', to='recipe.Unit'),
        ),
        migrations.AlterField(
            model_name='ingredientamount',
            name='amount',
            field=models.FloatField(blank=True, null=True, verbose_name='amount'),
        ),
        migrations.AlterField(
            model_name='ingredientamount',
            name='recipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingredient_amounts', to='recipe.Recipe'),
        ),
    ]
