# Generated by Django 2.2.12 on 2020-05-12 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0012_auto_20200511_0714'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='prep',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Preparation'),
        ),
        migrations.AlterField(
            model_name='nutrition',
            name='calories',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Calories (kcal)'),
        ),
        migrations.AlterField(
            model_name='nutrition',
            name='carbs',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Carbohydrates ()'),
        ),
        migrations.AlterField(
            model_name='nutrition',
            name='cholestrol',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Cholestrol ()'),
        ),
        migrations.AlterField(
            model_name='nutrition',
            name='fat',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Fat ()'),
        ),
        migrations.AlterField(
            model_name='nutrition',
            name='fiber',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Fiber ()'),
        ),
        migrations.AlterField(
            model_name='nutrition',
            name='protein',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Protein (g)'),
        ),
        migrations.AlterField(
            model_name='nutrition',
            name='sat_fat',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Saturated Fat ()'),
        ),
        migrations.AlterField(
            model_name='nutrition',
            name='servings',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Servings recommended ()'),
        ),
        migrations.AlterField(
            model_name='nutrition',
            name='sodium',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Sodium (mg)'),
        ),
        migrations.AlterField(
            model_name='nutrition',
            name='sugar',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Sugar (g)'),
        ),
        migrations.AlterField(
            model_name='nutrition',
            name='trans_fat',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Trans fat ()'),
        ),
        migrations.AlterField(
            model_name='nutrition',
            name='unsat_fat',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Unsaturated fat ()'),
        ),
    ]
