# Generated by Django 3.0.5 on 2020-04-10 03:36

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0013_auto_20200410_0335'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='ingredientamount',
            constraint=models.CheckConstraint(check=models.Q(amount__gt=Decimal('0')), name='amount_gt_0'),
        ),
    ]
