# Generated by Django 2.2.12 on 2020-06-01 03:05

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0013_auto_20200512_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='lazy_description',
            field=tinymce.models.HTMLField(default='', verbose_name='Lazy Text'),
        ),
    ]
