# Generated by Django 3.0.5 on 2020-04-10 03:51

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0014_auto_20200410_0336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredientamount',
            name='quantity',
        ),
        migrations.AlterField(
            model_name='ingredientamount',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('1'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='amount'),
        ),
    ]
