# Generated by Django 2.2.12 on 2020-06-01 03:15

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0016_direction_lazy_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direction',
            name='lazy_text',
            field=tinymce.models.HTMLField(default='', verbose_name='Lazy Text'),
        ),
    ]
