# Generated by Django 3.0.5 on 2020-04-10 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0017_auto_20200410_0419'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='direction',
        ),
    ]
