# Generated by Django 3.0.5 on 2020-04-10 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0019_auto_20200410_0552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direction',
            name='ingredient_amounts',
            field=models.ManyToManyField(blank=True, to='recipe.IngredientAmount'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(blank=True, through='recipe.IngredientAmount', to='recipe.Ingredient'),
        ),
    ]
