# Generated by Django 3.0.5 on 2020-04-10 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0020_auto_20200410_0552'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='direction',
            options={'ordering': ['direction_order'], 'verbose_name': 'Direction', 'verbose_name_plural': 'Directions'},
        ),
        migrations.RemoveField(
            model_name='direction',
            name='order',
        ),
        migrations.AddField(
            model_name='direction',
            name='direction_order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
        ),
    ]
