# Generated by Django 3.0.5 on 2020-04-10 06:28

import adminsortable.fields
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0021_auto_20200410_0626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direction',
            name='recipe',
            field=adminsortable.fields.SortableForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='directions', to='recipe.Recipe'),
        ),
    ]
