# Generated by Django 3.0.5 on 2020-04-10 23:01

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0022_auto_20200410_0628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direction',
            name='text',
            field=models.TextField(blank=True, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='ingredientamount',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('1'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='name',
            field=models.CharField(max_length=60, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='name_abbrev',
            field=models.CharField(blank=True, max_length=60, verbose_name='Abbreviation'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='plural_abbrev',
            field=models.CharField(blank=True, max_length=60, verbose_name='Plural Abbreviation'),
        ),
    ]
