# Generated by Django 3.0.5 on 2020-04-10 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0023_auto_20200410_2301'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='use_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
