# Generated by Django 3.0.5 on 2020-04-10 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0024_ingredient_use_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='createdAt',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='modifiedAt',
            new_name='modified_at',
        ),
    ]
