# Generated by Django 3.0.5 on 2020-04-13 21:48

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('recipe', '0027_recipe_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='image_url',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recipe',
            name='large_image_url',
            field=models.URLField(default='https://via.placeholder.com/1000', max_length=300),
        ),
        migrations.AddField(
            model_name='recipe',
            name='med_image_url',
            field=models.URLField(default='https://via.placeholder.com/400', max_length=300),
        ),
        migrations.AddField(
            model_name='recipe',
            name='sm_image_url',
            field=models.URLField(default='https://via.placeholder.com/150', max_length=300),
        ),
    ]
