# Generated by Django 3.0.5 on 2020-04-15 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0029_recipe_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='likes',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
