# Generated by Django 3.0.5 on 2020-04-15 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0030_recipe_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='description',
            field=models.TextField(default='', verbose_name='Text'),
        ),
    ]
