# Generated by Django 3.0.5 on 2020-04-16 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0031_recipe_description'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='direction',
            constraint=models.UniqueConstraint(fields=('recipe', 'text'), name='no duplicate direction per recipe'),
        ),
    ]
