# Generated by Django 3.0.5 on 2020-04-16 18:01

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0032_auto_20200416_0100'),
    ]

    operations = [
        migrations.AddField(
            model_name='direction',
            name='rich_text',
            field=tinymce.models.HTMLField(default=''),
        ),
    ]
