# Generated by Django 3.0.5 on 2020-04-16 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0033_direction_rich_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='direction',
            name='rich_text',
        ),
    ]
