# Generated by Django 3.0.5 on 2020-04-16 18:29

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0034_remove_direction_rich_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='direction',
            name='rich_text',
            field=tinymce.models.HTMLField(default=''),
        ),
    ]
