# Generated by Django 3.0.5 on 2020-04-16 20:15

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0036_remove_direction_rich_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direction',
            name='text',
            field=tinymce.models.HTMLField(default='', verbose_name='Text'),
        ),
    ]
