# Generated by Django 3.0.5 on 2020-04-16 20:35

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0037_auto_20200416_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='description',
            field=tinymce.models.HTMLField(default='', verbose_name='Text'),
        ),
    ]
