# Generated by Django 3.0.5 on 2020-04-17 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0039_auto_20200417_1859'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='tags',
        ),
    ]
