# Generated by Django 3.0.5 on 2020-04-20 02:32

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('recipe', '0041_auto_20200420_0141'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RecipeTag',
            new_name='MyCustomTag',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
