# Generated by Django 3.0.5 on 2020-04-20 02:32

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0042_auto_20200420_0232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='recipe.TaggedWhatever', to='recipe.MyCustomTag', verbose_name='Tags'),
        ),
    ]
