# Generated by Django 2.2.12 on 2020-04-20 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0043_auto_20200420_0232'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MyCustomTag',
            new_name='RecipeTag',
        ),
    ]
