# Generated by Django 2.2.12 on 2020-04-22 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0045_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taggedwhatever',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='taggedwhatever',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='RecipeTag',
        ),
        migrations.DeleteModel(
            name='TaggedWhatever',
        ),
    ]
