# Generated by Django 2.2.12 on 2020-04-22 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200422_2219'),
        ('recipe', '0047_recipe_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Series'),
        ),
    ]
