# Generated by Django 2.2.12 on 2020-04-24 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0049_auto_20200422_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='name',
            field=models.CharField(default='k', max_length=500, unique=True),
            preserve_default=False,
        ),
    ]
