# Generated by Django 2.2.12 on 2020-04-25 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0050_auto_20200424_0439'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='short_description',
            field=models.TextField(default=''),
        ),
    ]
