# Generated by Django 2.2.12 on 2020-04-26 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_privateimage_publicimage'),
        ('recipe', '0051_recipe_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.PublicImage'),
        ),
    ]
