# Generated by Django 2.2.12 on 2020-04-27 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0052_recipe_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='max_servings',
            field=models.PositiveSmallIntegerField(default=25),
        ),
    ]
