# Generated by Django 2.2.12 on 2020-04-22 22:19

from django.db import migrations
import taggit.managers
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_series'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='description',
            field=tinymce.models.HTMLField(default='', verbose_name='Text'),
        ),
        migrations.AddField(
            model_name='series',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='core.TaggedWhatever', to='core.BasicTag', verbose_name='Tags'),
        ),
    ]
