# Generated by Django 2.2.12 on 2020-04-22 22:47

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200422_2219'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='series',
            options={'ordering': ['name'], 'verbose_name': 'Series', 'verbose_name_plural': 'Seriess'},
        ),
        migrations.AlterField(
            model_name='series',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='core.TaggedWhatever', to='core.BasicTag', verbose_name='Tags'),
        ),
    ]
