# Generated by Django 2.2.12 on 2020-04-22 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200422_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='name',
            field=models.CharField(default='sd', max_length=500, unique=True),
            preserve_default=False,
        ),
    ]
