# Generated by Django 2.2.12 on 2020-05-06 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_series_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='slug',
            field=models.SlugField(default='', editable=False, max_length=100),
            preserve_default=False,
        ),
    ]
