# Generated by Django 2.2.12 on 2020-04-26 21:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import misoboop.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0005_auto_20200422_2248'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('upload', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='PrivateImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('upload', models.ImageField(storage=misoboop.storage_backends.PrivateMediaStorage, upload_to='')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
