# Generated by Django 2.2.12 on 2020-04-27 00:05

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_privateimage_publicimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='privateimage',
            name='description',
            field=tinymce.models.HTMLField(default='', verbose_name='Text'),
        ),
        migrations.AddField(
            model_name='privateimage',
            name='name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='publicimage',
            name='description',
            field=tinymce.models.HTMLField(default='', verbose_name='Text'),
        ),
        migrations.AddField(
            model_name='publicimage',
            name='name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
