# Generated by Django 2.2.13 on 2020-06-15 22:43

from django.db import migrations
import misoboop.storage_backends
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_basictag_is_cuisine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privateimage',
            name='upload',
            field=sorl.thumbnail.fields.ImageField(storage=misoboop.storage_backends.PublicMediaStorage, upload_to=''),
        ),
    ]
