# Generated by Django 2.2.12 on 2020-04-27 00:06

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200427_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privateimage',
            name='description',
            field=tinymce.models.HTMLField(blank=True, default='', null=True, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='publicimage',
            name='description',
            field=tinymce.models.HTMLField(blank=True, default='', null=True, verbose_name='Text'),
        ),
    ]
