# Generated by Django 2.2.13 on 2020-06-22 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20200615_2243'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PrivateImage',
        ),
    ]
