# Generated by Django 2.2.12 on 2020-04-27 00:42

from django.db import migrations
import misoboop.storage_backends
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20200427_0006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privateimage',
            name='upload',
            field=sorl.thumbnail.fields.ImageField(storage=misoboop.storage_backends.PrivateMediaStorage, upload_to=''),
        ),
        migrations.AlterField(
            model_name='publicimage',
            name='upload',
            field=sorl.thumbnail.fields.ImageField(upload_to=''),
        ),
    ]
