version: 2
jobs:
  build-and-test:
    docker:
      - image: circleci/python:3.6.9
        environment: 
          DATABASE_URL: postgresql://root:@localhost/circle_test?sslmode=disable
      - image: circleci/postgres:10.12
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: circle_test
          POSTGRES_PASSWORD: password
    steps:
    - checkout
    - restore_cache:
        keys:
        - pip-{{ checksum "requirements.txt"  }}
    - run:
        command: |
          if true; then
            pip install --user -r requirements.txt
          else
            pip install -r requirements.txt
          fi
        name: Install Dependencies
    - save_cache:
        key: pip-{{ checksum "requirements.txt"  }}
        paths:
        - /home/circleci/.local/lib/
    - run:
        command: |
          python -m pytest -v --ds=misoboop.settings_test --junitxml=test-results/pytest/pytest-report.xml
        name: Test
    - store_test_results: # Upload test results for display in Test Summary: https://circleci.com/docs/2.0/collect-test-data/
        path: test-results
    - store_artifacts: # Upload test summary for display in Artifacts: https://circleci.com/docs/2.0/artifacts/
        path: test-results
        destination: tr1
    - run:
        command: |
          bash <(curl -s https://codecov.io/bash)
          
workflows:
  main:
    jobs:
    - build-and-test
  version: 2
