# Generated by Django 2.2.12 on 2020-04-30 02:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('headline', models.CharField(max_length=300, unique=True, verbose_name='Headline')),
                ('alt_headline', models.CharField(blank=True, max_length=300, null=True, verbose_name='Alternative headline')),
                ('short_description', models.TextField(blank=True, default='', null=True)),
                ('content', tinymce.models.HTMLField(default='', verbose_name='Text')),
                ('slug', models.SlugField(editable=False, max_length=100)),
                ('is_published', models.BooleanField(default=False)),
                ('image_url', models.URLField(default='https://via.placeholder.com/150', max_length=300)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
                'ordering': ['created_at', 'modified_at', 'headline'],
            },
        ),
    ]
