# Generated by Django 2.2.12 on 2020-05-06 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200505_2117'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='image_url',
            new_name='placeholder_url',
        ),
    ]
