# Generated by Django 2.2.12 on 2020-04-22 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200422_2219'),
        ('blog', '0005_auto_20200422_0328'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Series'),
        ),
    ]
