# Generated by Django 2.2.12 on 2020-04-28 15:50

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20200428_0009'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='summary',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Summary'),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=tinymce.models.HTMLField(blank=True, default='', null=True, verbose_name='Text'),
        ),
    ]
