# Generated by Django 2.2.12 on 2020-04-28 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20200428_1558'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='text',
            new_name='content',
        ),
        migrations.AddField(
            model_name='post',
            name='alt_headline',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Alternative headline'),
        ),
    ]
