# Generated by Django 2.2.12 on 2020-04-28 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20200428_1550'),
        ('blog', '0010_post_short_description'),
    ]

    operations = [
    ]
