# Generated by Django 2.2.12 on 2020-04-28 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_merge_20200428_1743'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='summary',
        ),
    ]
