# Generated by Django 2.2.12 on 2020-04-29 04:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20200427_0042'),
        ('blog', '0013_post_is_published'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['headline', 'created_at', 'modified_at'], 'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.PublicImage'),
        ),
        migrations.AddField(
            model_name='post',
            name='image_url',
            field=models.URLField(default='https://via.placeholder.com/150', max_length=300),
        ),
    ]
